### PR TITLE
Various updates: LibGDX, coroutines, mockito, gradle, etc

### PR DESCRIPTION
**Pull request by maltaisn**
LibGDX 1.9.10 was released a few days ago with a few changes. I took the opportunity to also update the kotlin version to 1.3.41 and the coroutines to a version that matched the kotlin version. I also updated a few testing frameworks, I hope you don't mind.

All tests pass. There might some changes to do with the new `Tree.Node` generics since `KNode` hides them for now.

### CODE REVIEW

**Comment by czyzby** [comment]
Thanks for the update! Make sure to update the `CHANGELOG` when you change versions of major libraries. It's all described [here](https://github.com/libktx/ktx/blob/master/.github/CONTRIBUTING.md#updating-dependencies).

**Comment by czyzby** [comment]
KTX `1.9.10-SNAPSHOT` should be already available. I'll release `1.9.10-b1` once stable VisUI matching latest LibGDX version is released.

**Comment by czyzby** [comment]
#199

**Comment by maltaisn** [comment]
Gradle can't resolve the `1.9.10-SNAPSHOT` version on maven.

**Comment by czyzby** [comment]
Because it's a snapshot, Maven Central shows only stable releases. [Snapshots seem to be properly uploaded](https://oss.sonatype.org/content/repositories/snapshots/io/github/libktx/ktx-app/). You just have to add the snapshot repository to your Gradle setup in order to use them.

**Pull request merged**
