### PR TITLE
Type-safe enum names without invoke() method and brackets

### PR DESCRIPTION
**Pull request by FocusPo1nt**
Example:

enum class Drawables {
buttonUp,
buttonDown,
buttonChecked;
}

skin(myAtlas) {
button {
up = it[buttonUp]
down = it[buttonDown]
}
}

### CODE REVIEW

**Comment by czyzby** [comment]
I wanted to avoid enum utilities, since they are can be very application-specific, but one actually seems pretty generic. Thanks!

Could you write some simple unit tests for your utilities? You can see some examples [in this file](https://github.com/libktx/ktx/blob/master/style/src/test/kotlin/ktx/style/styleTest.kt).

**Comment by FocusPo1nt** [comment]
I added the test.

From Style documentation: "..we encourage you to store your drawables, fonts, colors and non-default styles names as enums to ensure complete safely at compile time."

I like this approach. I just wanted to make it more readable a little bit

**Comment by czyzby** [comment]
Yeah, it's a very good idea. I'll update the README as well.

**Comment by czyzby** [comment]
Thanks.

**Pull request merged**
