### PR TITLE
Image builders

### LINKED ISSUE #299: Image builder without Skin styles
Now `image` builder have only one option - define skin and stylename. But I merge my sources into atlases and skins only before release (it is much faster to debug and make changes with direct access to texture files).

Right now I use 'ktx-vis' just to make things like:
```kotlin
visImage(Texture("texture.png"))
```
as VisUI had `Image` constructors for Texture/Drawable/NinePatch/etc. before official Libgdx added them. But now they are in official libgdx, so it would be nice to have them in `ktx-scene2d`.

Another handy thing would be to add `image` to `skin` builder and use it like:
```kotlin
// define in skin
skin {
    image("myImage") {
        drawable = ... // put drawable here from texture or smth
    }
}
...
// use in ui
table {
    label("Text")
    image("myImage") {
        setSize(50f, 50f)
    }
}
```

### PR DESCRIPTION
**Pull request by Divelix**
I just added builders for NinePatch, TextureRegion, Texture, drawable and related tests. Fixes #299

### CODE REVIEW

**Comment by czyzby** [comment]
By the way, always make pull requests to the `develop` branch. This branch has the latest changes and is used to build and upload the snapshot versions. `master` is only for the stable releases.

**Comment by Divelix** [comment]
Updated changelog and docs (I used `...` to make it look concise and on point, not sure if its ok).

**Comment by czyzby** [comment]
It's OK, although I meant the source documentation (kdocs), not the README file. It's fine though - there's never enough usage examples. :)

**Comment by Divelix** [comment]
Oh, you meant kdocs, ok. If I want to add them, or that skin builder, should I make another PR, or keep this one?

**Comment by czyzby** [comment]
It's OK, I've already added them myself. See the latest commit linked to #299. Thanks again for the contribution.

**Pull request merged**
