### PR TITLE
Added json extensions module

### PR DESCRIPTION
**Pull request by maltaisn**
Improves syntax with type inference and improves type safety of LibGDX Json reader and writer. The module doesn't add anything new, just reified extension function.

I didn't do the readme yet because I realized this module doesn't add any functionality apart from syntax, unlike other modules. For the same reason, only minimal tests were made.

### CODE REVIEW

**Comment by czyzby** [comment]
Thanks for the PR, I'll review it soon.

Keep in mind that the PRs should be made to `develop` branch rather than `master`. I know it's a bit confusing since the `master` branch is the default one, but this is deliberate - I want people to browse the relevant code that they would find in the current Maven release rather than new features, which might not be included yet.

> I didn't do the readme yet because I realized this module doesn't add any functionality apart from syntax, unlike other modules.

That's not entirely true, `ktx-math` and `ktx-collections` are basically syntax sugar modules and they still list all of the functionalities and show you some practical examples. I'd like to keep this sort of documentation for every module. I could still accept the PR without it, but keep in mind I'll not merge it into `master` and include in the next release before writing such documentation myself. I think the documentation is what made people use and contribute to this library in the first place. :)

> For the same reason, only minimal tests were made.

I agree that you shouldn't test the whole LibGDX JSON API, but please make sure each included extension method is tested by at least one test case.

**Comment by maltaisn** [comment]
> Keep in mind that the PRs should be made to `develop` branch rather than `master`.

If I did it correctly, the commit was made on a new `maltaisn/json` branch, branched from the `maltaisn/develop` branch (which may not be up-to-date with `libktx/develop`). I created a new branch since I intended to do many commits (which I haven't made yet).

> I agree that you shouldn't test the whole LibGDX JSON API, but please make sure each included extension method is tested by at least one test case.

I'll make the tests soon.

I'll also do the readme following the structure of other readmes, and mentioning the fact that other serialization libraries exist and should be preferred in some cases.

**Comment by czyzby** [comment]
You used the correct branch, but made the request to merge into `libktx:master` rather than `libktx:develop`. Don't worry, I changed it already.

**Comment by maltaisn** [comment]
I added some tests and made a readme draft, you can complete it if anything is missing.

**Comment by czyzby** [comment]
There are only minor changes required (e.g. missing trailing new lines in some files), but I can correct these manually. Thanks for the contribution.

**Comment by czyzby** [comment]
Somehow passing `name: String, jsonData: JsonValue` in that order feels wrong. I'd include `jsonData` as the first parameter in most methods, but I understand consistency with LibGDX API might be more important in this case.

**Comment by czyzby** [comment]
Not sure if you were aware of this, but you can use Kotlin data classes along with LibGDX `Json` API as long as you manage to provide defaults for each variable. You can check the latest commits to develop to see my slight refactoring.

Anyway, a snapshot of the libraries is being uploaded to Maven as I'm writing this. Thanks again for the contribution.

**Comment by maltaisn** [comment]
> Somehow passing `name: String, jsonData: JsonValue` in that order feels wrong.

As you said that was for consistency with the original API but I agree the order feels wrong. In fact, if we put name after, the two `readValue` methods could be merged into a single one with a default argument value of `null` for name. (Same for `readArrayValue`)


> Not sure if you were aware of this, but you can use Kotlin data classes along with LibGDX `Json` API as long as you manage to provide defaults for each variable. You can check the latest commits to develop to see my slight refactoring.

No I didn't know thanks! I just checked the Kotlin documentation:

> Note that, as described in Secondary Constructors, if a class has default values for all constructor parameters, a public no-argument constructor will be generated for it. This works even if the `@JvmOverloads annotation is not specified.

So it should work with all classes not just data classes.

**Comment by czyzby** [comment]
> As you said that was for consistency with the original API but I agree the order feels wrong. In fact, if we put name after, the two `readValue` methods could be merged into a single one with a default argument value of `null` for name. (Same for `readArrayValue`)

Now I'm tempted to do that. Our goal is to improve LibGDX after all.

> So it should work with all classes not just data classes.

Yes, it's just that data classes are the most useful in terms of serialized data objects.

**Pull request merged**
